#ifndef OREPL_LEXER_H_IS_INCLUDED
#define OREPL_LEXER_H_IS_INCLUDED

enum OreplToken {
	OREPL_TOKEN_LET,
	OREPL_TOKEN_CONST,

	OREPL_TOKEN_STRING,
	OREPL_TOKEN_NUMBER,

	OREPL_TOKEN_TRUE,
	OREPL_TOKEN_FALSE,
	OREPL_TOKEN_NULL,

	OREPL_TOKEN_BRACE_LEFT,
	OREPL_TOKEN_BRACE_RIGHT,

	OREPL_TOKEN_BRACKET_LEFT,
	OREPL_TOKEN_BRACKET_RIGHT,

	OREPL_TOKEN_PAREN_LEFT,
	OREPL_TOKEN_PAREN_RIGHT,

	OREPL_TOKEN_COMMA,
	OREPL_TOKEN_FULL_STOP,

	OREPL_TOKEN_LESS_THAN_SIGN,
	OREPL_TOKEN_GREATER_THAN_SIGN,

	OREPL_TOKEN_SEMI_COLON,
	OREPL_TOKEN_COLON,

	OREPL_TOKEN_PLUS,
	OREPL_TOKEN_MINUS,

	OREPL_TOKEN_TILDE_SIGN,
	OREPL_TOKEN_EXCLAMATION_MARK,
	OREPL_TOKEN_AT_SIGN,
	OREPL_TOKEN_HASH_SIGN,
	OREPL_TOKEN_DOLLAR_SIGN,

	OREPL_TOKEN_PERCENT_SIGN,
	OREPL_TOKEN_CARET_SIGN,
	OREPL_TOKEN_AMPERSAND_SIGN,
	OREPL_TOKEN_ASTERISK,

	OREPL_TOKEN_UNDERSCORE,
	OREPL_TOKEN_EQUAL_SIGN,

	OREPL_TOKEN_QUESTION_MARK,
	OREPL_TOKEN_SLASH,
	OREPL_TOKEN_BACKSLASH,
	OREPL_TOKEN_PIPE,

	OREPL_TOKEN_NONE
};



#endif